
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import type { RouteHistory, VehicleHistoryPoint, RouteSegment } from '@/lib/types';

const newVehicleHistoryData = {
    "groups": [
        {
            "id_estado": "5",
            "count": 18,
            "total_time_seconds": 450,
            "total_time_formatted": "7m 30s",
            "avg_velocidad": 2.56,
            "max_velocidad": 9,
            "total_distance_km": 0.099,
            "start_coords": "-14.1563016,-75.7047516",
            "end_coords": "-14.15666,-75.7052066",
            "records": [
                {
                    "id": "7688",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.69",
                    "temperatura": "0.00",
                    "senal_gsm": -1,
                    "nivel_bateria_vehicular": "27.46",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985777,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7689",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.69",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985817,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7690",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.44",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985857,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7691",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.50",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985897,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7692",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.90",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985937,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7693",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.90",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985977,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7694",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.704705",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986017,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7695",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047033",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986057,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7696",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047033",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986097,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7697",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047016",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.83",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986137,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7698",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7046983",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986177,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7699",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1564516,-75.704625",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 176,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986190,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7700",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565333,-75.704625",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "5.00",
                    "rumbo": 208,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.68",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986195,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7701",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565716,-75.7046533",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "5.00",
                    "rumbo": 230,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.61",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986199,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7702",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565883,-75.7046833",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "6.00",
                    "rumbo": 256,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986201,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7703",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15659,-75.7046966",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 277,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.64",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986203,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7704",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565866,-75.7048533",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 257,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.58",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986210,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7705",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15666,-75.7052066",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "9.00",
                    "rumbo": 281,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.77",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986227,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                }
            ]
        },
        {
            "id_estado": "7",
            "count": 29,
            "total_time_seconds": 753,
            "total_time_formatted": "12m 33s",
            "avg_velocidad": 31.52,
            "max_velocidad": 65,
            "total_distance_km": 6.391,
            "start_coords": "-14.155835,-75.70621",
            "end_coords": "-14.2040316,-75.71428",
            "records": [
                {
                    "id": "7706",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.155835,-75.70621",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "17.00",
                    "rumbo": 294,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 28,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986270,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7707",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1554533,-75.7078716",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "11.00",
                    "rumbo": 272,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986307,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7708",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15552,-75.71042",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "35.00",
                    "rumbo": 268,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.72",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986347,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7709",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1555783,-75.7119866",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "11.00",
                    "rumbo": 269,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 28,
                    "nivel_bateria_vehicular": "27.60",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986387,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7710",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1556716,-75.7132783",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 270,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.58",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986427,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7711",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1556733,-75.7132816",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 220,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.33",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986467,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7712",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15568,-75.7133483",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "5.00",
                    "rumbo": 255,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986478,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7713",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15575,-75.713495",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "8.00",
                    "rumbo": 234,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986489,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7714",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.159135,-75.7130183",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "45.00",
                    "rumbo": 170,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986535,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7715",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1636816,-75.7121266",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "52.00",
                    "rumbo": 165,
                    "odometro": "9051.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 23,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986575,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7716",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1670166,-75.711585",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "60.00",
                    "rumbo": 186,
                    "odometro": "9052.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986598,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7717",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1675933,-75.7117716",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "60.00",
                    "rumbo": 208,
                    "odometro": "9052.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.66",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986602,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7718",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1679366,-75.7120666",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "59.00",
                    "rumbo": 228,
                    "odometro": "9052.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.70",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986605,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7719",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1692266,-75.7133483",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "61.00",
                    "rumbo": 206,
                    "odometro": "9052.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986617,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7720",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1734933,-75.7152166",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "65.00",
                    "rumbo": 205,
                    "odometro": "9053.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 13,
                    "nivel_bateria_vehicular": "27.71",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986646,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7721",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1759633,-75.716005",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "60.00",
                    "rumbo": 185,
                    "odometro": "9053.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986662,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7722",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.181595,-75.71518",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "61.00",
                    "rumbo": 167,
                    "odometro": "9054.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.66",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986698,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7723",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1861333,-75.7143316",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "50.00",
                    "rumbo": 173,
                    "odometro": "9054.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.67",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986731,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7724",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1891466,-75.7143633",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "25.00",
                    "rumbo": 182,
                    "odometro": "9054.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 22,
                    "nivel_bateria_vehicular": "27.67",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986771,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7725",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.19136,-75.714125",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "41.00",
                    "rumbo": 162,
                    "odometro": "9055.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 18,
                    "nivel_bateria_vehicular": "27.64",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986796,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7726",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1926816,-75.7138183",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "39.00",
                    "rumbo": 183,
                    "odometro": "9055.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 20,
                    "nivel_bateria_vehicular": "27.61",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986809,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7727",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1948116,-75.7143683",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "34.00",
                    "rumbo": 195,
                    "odometro": "9055.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.67",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986849,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7728",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1991466,-75.7154416",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "42.00",
                    "rumbo": 183,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.56",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986890,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7729",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.203495,-75.7147616",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "42.00",
                    "rumbo": 166,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.57",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986930,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7730",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040566,-75.7146033",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "13.00",
                    "rumbo": 142,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.42",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986938,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7731",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040883,-75.714555",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "10.00",
                    "rumbo": 111,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.38",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986940,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7732",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040916,-75.7144883",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "8.00",
                    "rumbo": 80,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.48",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986943,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7733",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040316,-75.71428",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 67,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.71",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.41",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986983,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7734",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040316,-75.71428",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 67,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.43",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987023,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                }
            ]
        },
        {
            "id_estado": "5",
            "count": 2,
            "total_time_seconds": 40,
            "total_time_formatted": "40s",
            "avg_velocidad": 0,
            "max_velocidad": 0,
            "total_distance_km": 0,
            "start_coords": "-14.2040316,-75.71428",
            "end_coords": "-14.20403,-75.71428",
            "records": [
                {
                    "id": "7735",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2040316,-75.71428",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 67,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.34",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987063,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7736",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.20403,-75.71428",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 67,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.50",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987103,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                }
            ]
        },
        {
            "id_estado": "7",
            "count": 76,
            "total_time_seconds": 2608,
            "total_time_formatted": "43m 28s",
            "avg_velocidad": 16.72,
            "max_velocidad": 54,
            "total_distance_km": 12.795,
            "start_coords": "-14.2039666,-75.7141683",
            "end_coords": "-14.147295,-75.6581666",
            "records": [
                {
                    "id": "7737",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2039666,-75.7141683",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 22,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 22,
                    "nivel_bateria_vehicular": "27.40",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987143,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7738",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2039333,-75.7141183",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "5.00",
                    "rumbo": 54,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 22,
                    "nivel_bateria_vehicular": "27.55",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987158,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7739",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2034716,-75.7135016",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "7.00",
                    "rumbo": 53,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 23,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987198,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7740",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.203025,-75.7128533",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "7.00",
                    "rumbo": 54,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.72",
                    "temperatura": "0.00",
                    "senal_gsm": 23,
                    "nivel_bateria_vehicular": "27.56",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987238,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7741",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2023383,-75.7117916",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "21.00",
                    "rumbo": 77,
                    "odometro": "9056.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.59",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987266,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7742",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.202695,-75.7109433",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "14.00",
                    "rumbo": 102,
                    "odometro": "9057.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.55",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987282,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7743",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2027216,-75.7102",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "7.00",
                    "rumbo": 82,
                    "odometro": "9057.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.47",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987309,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7744",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2023783,-75.7088966",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "29.00",
                    "rumbo": 62,
                    "odometro": "9057.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 17,
                    "nivel_bateria_vehicular": "27.58",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987341,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7745",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.2004966,-75.7052233",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "47.00",
                    "rumbo": 62,
                    "odometro": "9057.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.61",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987381,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7746",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1983483,-75.7010316",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "54.00",
                    "rumbo": 62,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 25,
                    "nivel_bateria_vehicular": "27.59",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987417,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7747",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1970883,-75.69854",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "7.00",
                    "rumbo": 75,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.55",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987457,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7748",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.196815,-75.6969416",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "30.00",
                    "rumbo": 80,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.56",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987497,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7749",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1966933,-75.6962683",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "9.00",
                    "rumbo": 58,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.32",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987508,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7750",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1966566,-75.69624",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "9.00",
                    "rumbo": 26,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.40",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987510,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7751",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1966333,-75.696235",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "8.00",
                    "rumbo": 5,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.21",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987511,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7752",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.19659,-75.6962416",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "8.00",
                    "rumbo": 343,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.74",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.42",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987513,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7753",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1962316,-75.6962983",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "14.00",
                    "rumbo": 355,
                    "odometro": "9058.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.73",
                    "temperatura": "0.00",
                    "senal_gsm": 20,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987553,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7754",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1941433,-75.6963833",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "5.00",
                    "rumbo": 354,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.74",
                    "temperatura": "0.00",
                    "senal_gsm": 21,
                    "nivel_bateria_vehicular": "27.27",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987593,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7755",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1923366,-75.696445",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "26.00",
                    "rumbo": 354,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.74",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.54",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987633,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7756",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1912733,-75.6964816",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "14.00",
                    "rumbo": 357,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.74",
                    "temperatura": "0.00",
                    "senal_gsm": 22,
                    "nivel_bateria_vehicular": "27.54",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987673,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7757",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1909966,-75.6964933",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "0.00",
                    "rumbo": 4,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.74",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.20",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987713,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7758",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.19049,-75.696535",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "19.00",
                    "rumbo": 358,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.75",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.50",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987753,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7759",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.18865,-75.696625",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "29.00",
                    "rumbo": 356,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.75",
                    "temperatura": "0.00",
                    "senal_gsm": 19,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987793,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7760",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.18663,-75.696745",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "19.00",
                    "rumbo": 358,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.75",
                    "temperatura": "0.00",
                    "senal_gsm": 20,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987833,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7761",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1855366,-75.6967866",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "14.00",
                    "rumbo": 357,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.75",
                    "temperatura": "0.00",
                    "senal_gsm": 20,
                    "nivel_bateria_vehicular": "27.36",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987873,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7762",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1851066,-75.6967983",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "14.00",
                    "rumbo": 0,
                    "odometro": "9059.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.76",
                    "temperatura": "0.00",
                    "senal_gsm": 14,
                    "nivel_bateria_vehicular": "27.40",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987913,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7763",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1836616,-75.69686",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "19.00",
                    "rumbo": 356,
                    "odometro": "9060.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.76",
                    "temperatura": "0.00",
                    "senal_gsm": 26,
                    "nivel_bateria_vehicular": "27.53",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987953,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7764",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.18107,-75.6969466",
                    "tramas_validas": 1,
                    "id_estado": "7",
                    "velocidad": "6.00",
                    "rumbo": 0,
                    "odometro": "9060.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.76",
                    "temperatura": "0.00",
                    "senal_gsm": 27,
                    "nivel_bateria_vehicular": "27.52",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768987993,
                    "altitud": 0,
                    "codigo": 6,
                    "param1": "Transitando",
                    "param2": "El vehiculo esta transitando",
                    "param3": "#17C653",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                }
            ]
        },
        {
            "id_estado": "6",
            "count": 408,
            "total_time_seconds": 16280,
            "total_time_formatted": "4h 31m 20s",
            "avg_velocidad": 0,
            "max_velocidad": 0,
            "total_distance_km": 0.007,
            "start_coords": "-14.1635316,-75.67647",
            "end_coords": "-14.1635283,-75.676475",
            "records": []
        }
    ]
};

function parseCoords(coordenadas: string): { lat: number; lng: number } {
  const [lat, lng] = coordenadas.split(',').map(Number);
  return { lat, lng };
}

function mapNewToOldStatus(newStatus: string): string {
    switch(newStatus) {
        case '5': return '4'; // Ralenti -> Idle
        case '6': return '5'; // Estacionado -> Parked
        case '7': return '6'; // Transitando -> Moving
        default: return newStatus;
    }
}

export async function POST(req: NextRequest) {
  try {
    const { vehicleId } = await req.json();

    // In a real app, you would fetch data for vehicleId. We'll use the mock data.
    const segments: RouteSegment[] = newVehicleHistoryData.groups.map((group: any) => {
      const records = group.records;
      if (!records || records.length === 0) {
        // Create a placeholder record if none exist to avoid crashes,
        // which can happen for long "parked" segments.
        const [lat, lng] = group.start_coords.split(',').map(Number);
        records.push({
            coordenadas: group.start_coords,
            fecha: group.records[0]?.fecha || Math.floor(Date.now()/1000), // Fallback
            param1: 'Unknown',
        });
      }
      const firstRecord = records[0];
      const lastRecord = records[records.length - 1];

      return {
        id_estado: mapNewToOldStatus(group.id_estado),
        description: firstRecord.param1,
        durationMinutes: group.total_time_seconds / 60,
        distanceKm: group.total_distance_km,
        avgSpeed: group.avg_velocidad,
        startTime: firstRecord.fecha,
        endTime: lastRecord.fecha,
        startPoint: parseCoords(group.start_coords),
        endPoint: parseCoords(group.end_coords),
        records: records,
      };
    }).filter((s: RouteSegment | null): s is RouteSegment => s !== null && s.records.length > 0);

    const routePoints = segments
      .filter(s => s.id_estado === '6') // '6' is "Transitando" (Moving)
      .map(s => s.records.map(r => parseCoords(r.coordenadas)));

    const routeHistory: RouteHistory = { segments, routePoints };

    return NextResponse.json(routeHistory);
  } catch (error) {
    console.error("Error generating route:", error);
    return NextResponse.json({ error: 'Failed to generate route' }, { status: 500 });
  }
}
