
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import type { RouteHistory, VehicleHistoryPoint, RouteSegment } from '@/lib/types';

const newVehicleHistoryData = {
    "groups": [
        {
            "id_estado": "5",
            "count": 18,
            "total_time_seconds": 450,
            "total_time_formatted": "7m 30s",
            "avg_velocidad": 2.56,
            "max_velocidad": 9,
            "total_distance_km": 0.099,
            "start_coords": "-14.1563016,-75.7047516",
            "end_coords": "-14.15666,-75.7052066",
            "records": [
                {
                    "id": "7688",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.69",
                    "temperatura": "0.00",
                    "senal_gsm": -1,
                    "nivel_bateria_vehicular": "27.46",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985777,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7689",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.69",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985817,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7690",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563016,-75.7047516",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.44",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985857,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7691",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.50",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985897,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7692",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.90",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985937,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7693",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563033,-75.7047433",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 249,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.90",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768985977,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7694",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.704705",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986017,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7695",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047033",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 30,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986057,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7696",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047033",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.51",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986097,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7697",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7047016",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.83",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986137,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7698",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1563066,-75.7046983",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "0.00",
                    "rumbo": 114,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.49",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986177,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7699",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1564516,-75.704625",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 176,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986190,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7700",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565333,-75.704625",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "5.00",
                    "rumbo": 208,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.68",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986195,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7701",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565716,-75.7046533",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "5.00",
                    "rumbo": 230,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.61",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986199,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7702",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565883,-75.7046833",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "6.00",
                    "rumbo": 256,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.69",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986201,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7703",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15659,-75.7046966",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 277,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 31,
                    "nivel_bateria_vehicular": "27.64",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986203,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7704",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.1565866,-75.7048533",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "7.00",
                    "rumbo": 257,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.58",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986210,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                },
                {
                    "id": "7705",
                    "id_vehiculo": 643,
                    "coordenadas": "-14.15666,-75.7052066",
                    "tramas_validas": 1,
                    "id_estado": "5",
                    "velocidad": "9.00",
                    "rumbo": 281,
                    "odometro": "9050.00",
                    "horometro": "0.00",
                    "numero_satelites": 0,
                    "nivel_bateria": "3.70",
                    "temperatura": "0.00",
                    "senal_gsm": 24,
                    "nivel_bateria_vehicular": "27.77",
                    "id_cliente": 132,
                    "din": 10,
                    "fecha": 1768986227,
                    "altitud": 0,
                    "codigo": 4,
                    "param1": "Ralenti",
                    "param2": "Vehiculo estacionado con el motor apagado",
                    "param3": "#d63384",
                    "param4": "000000",
                    "created_at": "2025-12-17T15:46:46.078Z",
                    "updated_at": null
                }
            ]
        }
    ]
};

function parseCoords(coordenadas: string): { lat: number; lng: number } {
  const [lat, lng] = coordenadas.split(',').map(Number);
  return { lat, lng };
}

const descriptionMap: { [key: string]: string } = {
    '5': 'Ralenti',
    '6': 'Estacionado',
    '7': 'Transitando'
};


export async function POST(req: NextRequest) {
  try {
    const { vehicleId } = await req.json();

    const segments: RouteSegment[] = newVehicleHistoryData.groups.map((group: any) => {
      const records = group.records;
      if (!records || records.length === 0) {
          if (group.start_coords && group.end_coords) {
             const [startLat, startLng] = group.start_coords.split(',').map(Number);
             records.push({
                coordenadas: group.start_coords,
                fecha: Math.floor(Date.now()/1000) - 1000,
                param1: group.id_estado === '6' ? 'Parked' : 'Idle',
             });
             records.push({
                coordenadas: group.end_coords,
                fecha: Math.floor(Date.now()/1000),
                param1: group.id_estado === '6' ? 'Parked' : 'Idle',
             });
          } else {
            return null;
          }
      }
      const firstRecord = records[0];
      const lastRecord = records[records.length - 1];

      return {
        id_estado: group.id_estado,
        description: descriptionMap[group.id_estado as keyof typeof descriptionMap] || 'Unknown',
        durationMinutes: group.total_time_seconds / 60,
        distanceKm: group.total_distance_km,
        avgSpeed: group.avg_velocidad,
        startTime: firstRecord.fecha,
        endTime: lastRecord.fecha,
        startPoint: parseCoords(group.start_coords),
        endPoint: parseCoords(group.end_coords),
        records: records,
      };
    }).filter((s: RouteSegment | null): s is RouteSegment => s !== null && s.records.length > 0);

    const routePoints = segments
      .filter(s => s.id_estado === '7') // '7' is "Transitando" (Moving)
      .map(s => s.records.map(r => parseCoords(r.coordenadas)));

    const routeHistory: RouteHistory = { segments, routePoints };

    return NextResponse.json(routeHistory);
  } catch (error) {
    console.error("Error generating route:", error);
    return NextResponse.json({ error: 'Failed to generate route' }, { status: 500 });
  }
}
